security:
    providers:
        in_memory:
            memory: ~
        github_user_provider:
            id: github_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        homepage:
            pattern: ^/$
            anonymous: ~

        secured_area:
            pattern: ^/
            anonymous: ~
#            simple_preauth:
#                authenticator: github_authenticator
#            provider: github_user_provider
#            logout:
#                path:   /logout
#                target: /
